variables:
  AWS_DEFAULT_REGION: "us-east-1"
  TAGS: "terraform"

cache:
  paths:
    - .terraform
    
before_script:
  - terraform --version

stages:
  - init
  - validate
  - plan
  - apply
  - destroy

.init: 
  stage: init
  script:
    - terraform init
    - echo $SOURCE_DIR
    - cp $SOURCE_DIR/ci-templates/certifs.pem /usr/local/share/ca-certificates/certifs.pem
    - update-ca-certificates
    - git config --global url."https://dqvinh:$PAT_TOKEN@10.201.224.22".insteadOf https://10.201.224.22
    - echo $PAT_TOKEN
    - cat $SOURCE_DIR/ci-templates/certifs.pem
    - ls -la /usr/local/share/ca-certificates
  tags:
    - $TAGS

.validate:
  stage: validate
  script:
    - terraform validate
  tags:
    - $TAGS

.plan:
  stage: plan
  script:
    - terraform plan -out="planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
  tags:
    - $TAGS    

.apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
  tags:
    - $TAGS

.destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve
  when: manual
  tags:
    - $TAGS
